### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for FasterRCNNVGG16:

### ISSUE THREAD

**Issue by zcunyi** [Bigwode/rebar-detection-competition#1]
`RuntimeError: Error(s) in loading state_dict for FasterRCNNVGG16:
	size mismatch for head.cls_loc.bias: copying a param of torch.Size([8]) from checkpoint, where the shape is torch.Size([84]) in current model.
	size mismatch for head.cls_loc.weight: copying a param of torch.Size([8, 4096]) from checkpoint, where the shape is torch.Size([84, 4096]) in current model.
	size mismatch for head.score.bias: copying a param of torch.Size([2]) from checkpoint, where the shape is torch.Size([21]) in current model.
	size mismatch for head.score.weight: copying a param of torch.Size([2, 4096]) from checkpoint, where the shape is torch.Size([21, 4096]) in current model.
`
**Any help would be very much appreciated.**

**Comment by Bigwode** [comment]
@zcunyi Please download the pretrained caffe model according to the third part of the readme and specify the path in config.py. CHECK if you run
 python misc/convert_caffe_pretrain.py
before you train the model.

**Comment by zcunyi** [comment]
Thank you, I have figured it out. But there is another error:
`ValueError: Traceback (most recent call last):
  File "/data/image/zhangcunyi/pytorch/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/image/zhangcunyi/pytorch/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/image/zhangcunyi/YOLO/rebar-detection-competition/data/dataset.py", line 107, in __getitem__
    ori_img, bbox, label, difficult = self.db.get_example(idx)
  File "/data/image/zhangcunyi/YOLO/rebar-detection-competition/data/voc_dataset.py", line 120, in get_example
    label.append(VOC_BBOX_LABEL_NAMES.index(name))
ValueError: substring not found
`
