### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ghost** [Bigwode/rebar-detection-competition#6]
$ python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': '/usr/local/workspace/python/rebar-detection-competition/checkpoints/vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': './tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 2666,
 'min_size': 2000,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 1000,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/usr/local/workspace/python/VOC_GJ/',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
WARNING:root:Setting up a new session...
WARNING:visdom:Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    fire.Fire()
  File "/home/ajax/anaconda3/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/ajax/anaconda3/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/ajax/anaconda3/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 71, in train
    trainer.train_step(img, bbox, label, scale)
  File "/usr/local/workspace/python/rebar-detection-competition/trainer.py", line 169, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "/usr/local/workspace/python/rebar-detection-competition/trainer.py", line 100, in forward
    self.faster_rcnn.rpn(features, img_size, scale)  # roi_indices:[2000,0],anchor:[16650,4]
  File "/home/ajax/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/workspace/python/rebar-detection-competition/model/region_proposal_network.py", line 119, in forward
    scale=scale)
  File "/usr/local/workspace/python/rebar-detection-competition/model/utils/creator_tool.py", line 411, in __call__
    thresh=self.nms_thresh)
  File "/usr/local/workspace/python/rebar-detection-competition/model/utils/nms/non_maximum_suppression.py", line 26, in non_maximum_suppression
    return _non_maximum_suppression_gpu(bbox, thresh, score, limit)
  File "/usr/local/workspace/python/rebar-detection-competition/model/utils/nms/non_maximum_suppression.py", line 42, in _non_maximum_suppression_gpu
    sorted_bbox, thresh)
  File "/usr/local/workspace/python/rebar-detection-competition/model/utils/nms/non_maximum_suppression.py", line 125, in _call_nms_kernel
    mask_dev = cp.zeros((n_bbox * col_blocks,), dtype=np.uint64)
  File "/home/ajax/anaconda3/lib/python3.7/site-packages/cupy/creation/basic.py", line 147, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 151, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1065, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1086, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 900, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 921, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 695, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 18048000 bytes (total 18480128 bytes)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by ghost** [comment]
please help me
